### ISSUE TITLE
World-Class link missing

### ISSUE THREAD

**Issue by OzBob** [jstedfast/mimekit.net#2]
https://github.com/jstedfast/mimekit.net/blob/master/index.html#L253
to
http://www.mimekit.net/docs/html/ParsingMessages.htm
Does not exist in : https://github.com/jstedfast/mimekit.net/tree/master/docs/html

**Comment by OzBob** [comment]
https://github.com/jstedfast/mimekit.net/pull/3

**Comment by jstedfast** [comment]
thanks
